name: 'Setup Java JDK'
on: [pull_request]

permissions:
  contents: read
      
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Java ${{ matrix.Java }} sample
    steps:
      - name: 'Checkout Repository'
      - uses: actions/checkout@v3
      - name: 'Setup Java JDK'
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: java /Assignment1-Swing-Events/src/gui_swing_events/Main.java
